language: ruby
rvm:
        - 1.9.2
        - 1.9.3
        - rbx-19mode
        - ruby-head

   before_script:
  	- psql -c 'create database assignitapp_test;' -U postgres
  	- rake db:migrate
  	- rake db:test:prepare